services:
  website:
    depends_on:
      - db
    container_name: website
    image: website:latest
    networks:
      - web
    restart: always
    env_file: ".env"
  db:
    env_file: ".env"
    container_name: website_db
    image: postgres:15
    networks:
      - web
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - website_db:/var/lib/postgresql/data

networks:
  web:
    external: true

volumes:
  website_db:
