
name: Docker Image Build Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: czechclouds:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: ðŸŸ¢ Sending succes build info
      if: success()
      run: |
        WEBHOOK_URL="https://n8n.lahevodvika.eu/webhook-test/007a3735-e7e2-43d2-a9d2-2bd5511c9f82"
        
        PAYLOAD='{
          "status": "success",
          "build_result": "Docker image build succesfully.",
          "repository": "${{ github.repository }}",
          "pusher": "${{ github.triggering_actor }}",
          "event": "${{ github.event_name }}",
          "branch": "${{ github.ref_name }}",
          "sha": "${{ github.sha }}"
        }'
        
        echo "Sending succes build info..."
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          $WEBHOOK_URL
    
    - name: ðŸ”´ Sending failed build info
      if: failure()
      run: |
        WEBHOOK_URL="https://n8n.lahevodvika.eu/webhook-test/007a3735-e7e2-43d2-a9d2-2bd5511c9f82"
        
        PAYLOAD='{
          "status": "failure",
          "build_result": "Docker image build failed!",
          "repository": "${{ github.repository }}",
          "pusher": "${{ github.triggering_actor }}",
          "event": "${{ github.event_name }}",
          "branch": "${{ github.ref_name }}",
          "sha": "${{ github.sha }}"
        }'

        echo "Sending failed build info..."
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          $WEBHOOK_URL
