
name: Docker Image Build Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: czechclouds:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

  notify_n8n:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }} 
    
    steps:
    - name: Sending notification to N8n
      run: |
        WEBHOOK_URL="https://n8n.lahevodvika.eu/webhook-test/007a3735-e7e2-43d2-a9d2-2bd5511c9f82"
        BUILD_RESULT="${{ needs.build.result }}"
        
        if [ "$BUILD_RESULT" == "success" ]; then
          STATUS="success"
          MESSAGE="Docker image built succesfully."
        else
          STATUS="failure"
          MESSAGE="Docker image build failed. Result: $BUILD_RESULT"
        fi
        
        PAYLOAD='{
          "status": "'$STATUS'",
          "build_result": "'$MESSAGE'",
          "repository": "${{ github.repository }}",
          "pusher": "${{ github.triggering_actor }}",
          "event": "${{ github.event_name }}",
          "branch": "${{ github.ref_name }}",
          "sha": "${{ github.sha }}",
          "workflow_run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }'
        
        echo "Sending notification to N8N with data: $STATUS"
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          $WEBHOOK_URL
